version: '3.7'

services: # the different images that will be running as containers
  web: # service name
    build: . #build the image for the web service from the dockerfile in parent directory.
    # command directive passes the parameters to the service and they will be executed by the service. In this example, these are django commands which will be executed in the container where django lives.
    command: "python main.py"
    
    image: flask-docker-kub # name of the image

    expose: # expose the port to other services defined here so that they can access this service via the exposed port. In the case of Django, this is 8000 by default
      - 5000 # retrieved from the .env file
    restart: "on-failure"
   
